<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\District;
use Illuminate\Database\Seeder;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $branches = [
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0001',
                'type' => 'main_branch',
                'name' => 'Main Branch Muzaffarabad',
                'address' => 'Fatima Plaza, Chatter Domel Muzaffarabad',
                'latitude' => 34.3444400,
                'longitude' => 73.4664040,
                'facilities' => 'Safe Deposit Boxes, Foreign Exchange, Loan Services',
                'operating_hours' => [
                    'monday' => ['09:00', '17:00'],
                    'tuesday' => ['09:00', '17:00'],
                    'wednesday' => ['09:00', '17:00'],
                    'thursday' => ['09:00', '17:00'],
                    'friday' => [
                        'morning' => ['09:00', '13:00'],
                        'break' => ['13:00', '14:30'],
                        'afternoon' => ['14:30', '17:30'],
                    ],
                    'saturday' => ['09:00', '13:00'],
                    'sunday' => null,
                ],
                'is_24_hours' => false,
                'holidays' => ['2025-08-14', '2025-12-25'],
                'map_icon' => 'bank-main',
                'map_color' => '#007bff',
                'map_priority' => 1,
                'show_on_map' => true,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0002',
                'type' => 'main_branch',
                'name' => 'Main Branch Mirpur',
                'address' => 'Nishat Centre, Allama Iqbal Road, Mirpur',
                'latitude' => 33.1496860,
                'longitude' => 73.7405310,
                'facilities' => 'Safe Deposit Boxes, Foreign Exchange, Business Center',
                'operating_hours' => [
                    'monday' => ['09:00', '17:00'],
                    'tuesday' => ['09:00', '17:00'],
                    'wednesday' => ['09:00', '17:00'],
                    'thursday' => ['09:00', '17:00'],
                    'friday' => [
                        'morning' => ['09:00', '13:00'],
                        'break' => ['13:00', '14:30'],
                        'afternoon' => ['14:30', '17:30'],
                    ],
                    'saturday' => ['09:00', '13:00'],
                    'sunday' => null,
                ],
                'is_24_hours' => false,
                'map_icon' => 'bank-main',
                'map_color' => '#007bff',
                'map_priority' => 1,
                'show_on_map' => true,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0003',
                'name' => 'Dadyal Branch',
                'address' => 'Maqbool Butt Shaheed Chowk, Dadyal',
                'latitude' => 33.34315836451277,
                'longitude' => 73.6942343878139,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0004',
                'name' => 'Chaksawari Branch',
                'address' => 'Opposite Al-Shahzad Hotel Chaksawari',
                'latitude' => 33.2643920,
                'longitude' => 73.7847310,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0005',
                'name' => 'Kotli Branch',
                'address' => 'Poonch / Rawalpindi Road Kotli',
                'latitude' => 33.51606453787582,
                'longitude' => 73.90104590772751,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0006',
                'name' => 'Rawalakot Branch',
                'address' => 'Gulf Shopping Complex Katchari Road Rawalakot',
                'latitude' => 33.858990,
                'longitude' => 73.759644,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0007',
                'name' => 'Sehnsa Branch',
                'address' => 'Main Bazar Sehnsa AJK',
                'latitude' => 33.5118634,
                'longitude' => 73.7539954,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->region_id,
                'code' => '0008',
                'name' => 'Athmuqam Branch',
                'address' => 'Main Bazar Athmuqam District Neelum AJK',
                'latitude' => 34.5823260,
                'longitude' => 73.9040000,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0009',
                'name' => 'Islamgarh Branch',
                'address' => 'Main Bazar Islamgarh District Mirpur AJK',
                'latitude' => 33.1883240,
                'longitude' => 73.8318530,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bagh')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bagh')->first()->region_id,
                'code' => '0010',
                'name' => 'Bagh Branch',
                'address' => 'Main Bazar Bagh AJK',
                'latitude' => 33.97964040815748,
                'longitude' => 73.77576470775735,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bagh')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bagh')->first()->region_id,
                'code' => '0011',
                'name' => 'Arja Branch',
                'address' => 'Bagh/Rawalakot Chowk Arja District Bagh AJK',
                'latitude' => 33.974080545202874,
                'longitude' => 73.65809307952239,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->region_id,
                'code' => '0012',
                'name' => 'Bhimber Branch',
                'address' => 'Main Bazar Bhimber AJK',
                'latitude' => 32.97286637658382,
                'longitude' => 74.07278354472194,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0013',
                'name' => 'Pallandari Branch',
                'address' => 'Main Bazar Pallandari AJK',
                'latitude' => 33.7189950,
                'longitude' => 73.6865190,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0014',
                'name' => 'Nar Branch',
                'address' => 'Main Bazar Nar District Kotli AJK',
                'latitude' => 33.3941570,
                'longitude' => 73.8278080,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0015',
                'name' => 'F-3 Branch, Mirpur',
                'address' => 'Sector F-3 Mirpur AJK',
                'latitude' => 33.1376190,
                'longitude' => 73.7761200,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0016',
                'name' => 'Hajeera Branch',
                'address' => 'Main Bazar Hajeera District Poonch Azad Kashmir',
                'latitude' => 33.7705340,
                'longitude' => 73.8952010,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0017',
                'name' => 'Garhi-Dupata Branch',
                'address' => 'Pull Bazar Garhi Dupatta Muzaffarabad A.K',
                'latitude' => 34.2330880,
                'longitude' => 73.6087570,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0018',
                'name' => 'Lower Plate Branch',
                'address' => 'Near City Hospital Lower Plate Muzaffarabad A.K',
                'latitude' => 34.3787760,
                'longitude' => 73.4636900,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0019',
                'name' => 'Chatter Klass Branch',
                'address' => 'Kullian Bazar, Kohala-Muzaffarabad Road',
                'latitude' => 34.2021318540809,
                'longitude' => 73.49752386431247,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0020',
                'name' => 'Brahtla Branch',
                'address' => 'Main Bazar Brahtla District Kotli A.K',
                'latitude' => 33.3506850,
                'longitude' => 73.9081620,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0021',
                'name' => 'Khui Ratta Branch',
                'address' => 'Main Bazar Khui Ratta District Kotli A.K',
                'latitude' => 33.3610976151563,
                'longitude' => 74.02515210464392,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0022',
                'name' => 'Chakaar Branch',
                'address' => 'Main Bazar Chakaar District Muzaffarabad A.K',
                'latitude' => 34.1440270,
                'longitude' => 73.6784540,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bagh')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bagh')->first()->region_id,
                'code' => '0023',
                'name' => 'Dheerkot Branch',
                'address' => 'Main Bazar Dheerkot District Bagh A.K',
                'latitude' => 34.0350020,
                'longitude' => 73.5801450,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0024',
                'name' => 'Pathika Branch',
                'address' => 'Main Bazar Pathika District Muzaffarabad A.K',
                'latitude' => 34.4483890,
                'longitude' => 73.5477020,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0025',
                'name' => 'Bandi Abbaspur Branch',
                'address' => 'Pul Bazar Bandi Abbaspur District Poonch A.K',
                'latitude' => 33.815432021201744,
                'longitude' => 73.97591145962772,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0026',
                'name' => 'Sarsawa Branch',
                'address' => 'Main Bazar Sarsawa District Kotli A.K',
                'latitude' => 33.56384431409508,
                'longitude' => 73.85015463692226,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0027',
                'name' => 'Pulmanda Branch',
                'address' => 'Main Bazar Pulmanda District Mirpur A.K',
                'latitude' => 33.0551010,
                'longitude' => 73.7890450,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0028',
                'name' => 'Madina Market Branch',
                'address' => 'Madina Market District Muzaffarabad A.K',
                'latitude' => 34.37001689445499,
                'longitude' => 73.46888918109559,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->region_id,
                'code' => '0029',
                'name' => 'Barnala Branch',
                'address' => 'Main Bazar Barnala District Bhimber A.K',
                'latitude' => 32.87113945521126,
                'longitude' => 74.24405703207734,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0030',
                'name' => 'Khai-gala Branch',
                'address' => 'Main Bazar Khai-gala District Poonch A.K',
                'latitude' => 33.8452380,
                'longitude' => 73.8293180,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0031',
                'name' => 'Khad-Gujran Branch',
                'address' => 'Main Bazar Khad-Gujran District Kotli A.K',
                'latitude' => 33.5547500,
                'longitude' => 74.0103420,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0032',
                'name' => 'Trarkhal Branch',
                'address' => 'Main Bazar Tararkhal District Sudhanoti',
                'latitude' => 33.7628200,
                'longitude' => 73.7864950,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->region_id,
                'code' => '0033',
                'name' => 'Chowki Branch',
                'address' => 'Main Bazar Chowki District Bhimber A.K',
                'latitude' => 33.1196060,
                'longitude' => 74.0771860,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0034',
                'name' => 'Hattian Branch',
                'address' => 'Sakhi Plaza, Chowk Bazar, Hattian Bala',
                'latitude' => 32.871140981917634,
                'longitude' => 74.24403686072958,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->region_id,
                'code' => '0035',
                'name' => 'Poona Branch',
                'address' => 'Main Bazar Poona District Bhimber A.K',
                'latitude' => 33.18328254114515,
                'longitude' => 73.953816322494076,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0036',
                'name' => 'Charhoi Branch',
                'address' => 'Main Bazar Charhoi District Kotli A.K',
                'latitude' => 33.3004380,
                'longitude' => 73.9519820,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0037',
                'name' => 'Chakothi Branch',
                'address' => 'Main Bazar Chakhoti District Hattian A.K',
                'latitude' => 34.1161800,
                'longitude' => 73.8809340,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Haveli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Haveli')->first()->region_id,
                'code' => '0038',
                'name' => 'Kahotta Branch',
                'address' => 'Main Bazar Kahotta District Haveli A.K',
                'latitude' => 33.8837770,
                'longitude' => 74.1049840,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0039',
                'name' => 'Paniola Branch',
                'address' => 'Main Bazar Paniola District Poonch A.K',
                'latitude' => 33.94419138727132,
                'longitude' => 73.68438622853883,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0040',
                'name' => 'District Complex Muzaffarabad Branch',
                'address' => 'Old Secretariat District Complex District Muzaffarabd',
                'latitude' => 34.360031713165974,
                'longitude' => 73.47336133811272,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0041',
                'name' => 'Bloch Branch',
                'address' => 'Main Bazar Bloch District Sudhanoti',
                'latitude' => 33.64697175369556,
                'longitude' => 73.81571404179175,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0042',
                'name' => 'Tatta-Pani Branch',
                'address' => 'Main Bazar Tatta-Pani District Kotli A.K',
                'latitude' => 33.6036950,
                'longitude' => 73.9474890,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->region_id,
                'code' => '0043',
                'name' => 'Sharda Branch',
                'address' => 'Main Sharda Bazar District Neelum A.K',
                'latitude' => 34.7937680,
                'longitude' => 74.1836830,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0044',
                'name' => 'Mi-Toti Branch',
                'address' => 'Main Bazar Mi-Toti District Kotli A.K',
                'latitude' => 33.3267180,
                'longitude' => 74.0376000,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0045',
                'name' => 'Jatlan Branch',
                'address' => 'Main Bazar Jatlan District Mirpur',
                'latitude' => 33.0370430,
                'longitude' => 73.8390750,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0046',
                'name' => 'Mian Muhammad Town Branch',
                'address' => 'Mian Muhammad Town District Mirpur A.K',
                'latitude' => 33.1287290,
                'longitude' => 73.7471140,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0047',
                'name' => 'Jhatti Dheri Branch',
                'address' => 'Jhatti Dheri Cross District Mirpur A.K',
                'latitude' => 33.176650,
                'longitude' => 73.868881,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0048',
                'name' => 'Dhanna Branch',
                'address' => 'Dhanna Bazar District Kotli A.K',
                'latitude' => 33.4105790,
                'longitude' => 73.9974400,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0049',
                'name' => 'Talian Branch',
                'address' => 'Main Bazar Talian District Sadhnutti A.K',
                'latitude' => 33.6242950,
                'longitude' => 73.7653150,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0050',
                'name' => 'Thorar Branch',
                'address' => 'Main Bazar Thorar District Poonch A.K',
                'latitude' => 33.8491460,
                'longitude' => 73.6392790,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0051',
                'name' => 'Juna Branch',
                'address' => 'Main Bazar Juna District Kotli A.K',
                'latitude' => 33.3815800,
                'longitude' => 73.9421250,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->region_id,
                'code' => '0052',
                'name' => 'Joora Branch',
                'address' => 'Main Bazar Joora District Neelum A.K',
                'latitude' => 34.4927590,
                'longitude' => 73.8365990,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0053',
                'name' => 'Ladies Branch, Muzaffarabad',
                'address' => 'Hashim Plaza, Poultry Farm Road, Muzaffarabad, AK',
                'latitude' => 34.37120881140287,
                'longitude' => 73.46911381349467,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0054',
                'name' => 'Ladies Branch, Mirpur',
                'address' => 'Haris Plaza Chowk Shaheedan Sector C-2 Mirpur AK',
                'latitude' => 33.148989054858326,
                'longitude' => 73.74964578650533,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0055',
                'name' => 'Seharmandi Branch',
                'address' => 'Main Bazar Seharmandi, Tehsil Sehensa District Kotli AK',
                'latitude' => 33.4513230,
                'longitude' => 73.8166810,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0056',
                'name' => 'CMH Road Rawalakot Branch',
                'address' => 'CMH Road Rawalakot AK',
                'latitude' => 33.86364144175627,
                'longitude' => 73.75891473843073,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0057',
                'name' => 'Main Bazar Chakswari Branch',
                'address' => 'Main Bazar Chakswari Tehsil & District Mirpur AK',
                'latitude' => 33.2572500,
                'longitude' => 73.7745960,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0058',
                'name' => 'Ratta Branch Mirpur',
                'address' => 'Allah Abad Market Main Road Ratta Tehsil Dadyal Distt. Mirpur',
                'latitude' => 33.36352159556842,
                'longitude' => 73.66091948294321,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->region_id,
                'code' => '0059',
                'name' => 'Moil Branch',
                'address' => 'Tehsil & District Bhimber AK',
                'latitude' => 32.8384000,
                'longitude' => 74.3509930,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0060',
                'name' => 'Banbehk Branch',
                'address' => 'Tehsil & District Poonch',
                'latitude' => 33.8775600,
                'longitude' => 73.8262670,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0061',
                'name' => 'Upper Ada Branch',
                'address' => 'Near Shah Anayat Darbar Upper Ada Muzaffarabad',
                'latitude' => 34.3734790,
                'longitude' => 73.4722160,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0062',
                'name' => 'Chathian Branch',
                'address' => 'Srinagar Road, Chathian Bazar, Dist. Hattian Bala',
                'latitude' => 34.1930820,
                'longitude' => 73.6610920,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->region_id,
                'code' => '0063',
                'name' => 'Kutton Branch',
                'address' => 'Kutton, Tehsil Authmuqam, District Neelum',
                'latitude' => 34.56479200,
                'longitude' => 73.8012330,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0064',
                'name' => 'Jarahi Branch',
                'address' => 'Tehsil Dolya Jattan, District Kotli',
                'latitude' => 33.34606297511162,
                'longitude' => 73.79075187301063,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0065',
                'name' => 'Goi Branch',
                'address' => 'Village & P.O Goi Tehsil & District Kotli',
                'latitude' => 33.5557100,
                'longitude' => 74.0095680,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0066',
                'name' => 'Lorry Adda Branch',
                'address' => 'Lorry Adda, Tehsil & District Kotli, AJK',
                'latitude' => 33.5213409174677,
                'longitude' => 73.90719645379006,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0067',
                'name' => 'Gojra By-Pass Branch',
                'address' => 'Gojra By-Pass Road, Near WAPDA Colony, Muzaffarabad AJK',
                'latitude' => 34.3624610,
                'longitude' => 73.4621920,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0068',
                'name' => 'Mang Branch',
                'address' => 'Mang Bazar, Near AC Office, District Sudhnuti AJK',
                'latitude' => 33.7961310,
                'longitude' => 73.6326970,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Neelum')->first()->region_id,
                'code' => '0069',
                'name' => 'Kundal Shahi Branch',
                'address' => 'Main Bazar, Kundal Shahi, Tehsil Athmuqam, District Neelum',
                'latitude' => 34.5544730,
                'longitude' => 73.8469930,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0070',
                'name' => 'Brarkot Branch',
                'address' => 'Abbottabad Road Brarkot Tehsil & District Muzaffarabad A.K',
                'latitude' => 34.39593286485228,
                'longitude' => 73.38364374232978,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0071',
                'name' => 'Muslimabad Branch',
                'address' => 'Pattan Sher Khan, Tehsil Mang, District Sudhunoti, Azad Kashmir',
                'latitude' => 33.7963940,
                'longitude' => 73.5732730,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0072',
                'name' => 'Islam Nagar Branch',
                'address' => 'Pattan Sher Khan, Tehsil Mang, District Sudhunoti, Azad Kashmir',
                'latitude' => 33.7785890,
                'longitude' => 73.5717760,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->region_id,
                'code' => '0073',
                'name' => 'Samahni Branch',
                'address' => 'Shahrah-e-Jammu, Samahni, District Bhimber, Azad Kashmir',
                'latitude' => 33.0916640,
                'longitude' => 74.1308270,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0074',
                'name' => 'Panthal Branch',
                'address' => 'Panthal Branch, Tehsil and District Sudhanoti, Azad Kashmir',
                'latitude' => 33.6204650,
                'longitude' => 73.7231020,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0075',
                'name' => 'Nakyal Branch',
                'address' => 'Nakyal, Fatehpur Thakyala, District Kotli, Azad Kashmir',
                'latitude' => 33.4869397770142,
                'longitude' => 74.10349645378865,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0076',
                'name' => 'Chinari Branch',
                'address' => 'Main Bazar Chinari, Azad Kashmir',
                'latitude' => 34.1582040,
                'longitude' => 73.8243940,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0077',
                'name' => 'PM House Road Branch',
                'address' => 'Near PM House Muzaffarabad, Azad Kashmir',
                'latitude' => 34.3569240,
                'longitude' => 73.4742520,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bhimber')->first()->region_id,
                'code' => '0078',
                'name' => 'Kot Jamel Branch',
                'address' => 'Kot Jamel Tehsil Barnala Distt. Bhimber, Azad Kashmir',
                'latitude' => 32.8514810,
                'longitude' => 74.2994320,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0079',
                'name' => 'Kotli Road Branch Mirpur',
                'address' => 'Kotli Road branch opposite PWD Office Mirpur, Azad Kashmir',
                'latitude' => 33.1396580,
                'longitude' => 73.7676270,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0080',
                'name' => 'Mangla Hamlet',
                'address' => 'Main Bazar, Mangla Hamlet, Tehsil and District, Mirpur, Azad Kashmir',
                'latitude' => 33.102787572768975,
                'longitude' => 73.65180745192676,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0081',
                'name' => 'Khanabad',
                'address' => 'Khanabad Tehsil and District Mirpur, Azad Kashmir',
                'latitude' => 33.2912840,
                'longitude' => 73.7686950,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Kotli')->first()->region_id,
                'code' => '0082',
                'name' => 'Bypass Road Branch',
                'address' => 'Gulhar Shareef Chowk, Kotli, Azad Kashmir',
                'latitude' => 33.489908,
                'longitude' => 73.894195,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Poonch')->first()->region_id,
                'code' => '0083',
                'name' => 'Public Housing Scheme Branch',
                'address' => 'Bank Road Rawalakot (AK)',
                'latitude' => 33.8559170,
                'longitude' => 73.7566120,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0084',
                'name' => 'Main Bazar Leepa',
                'address' => 'Jhelum Valley (AJ&K)',
                'latitude' => 34.3013250,
                'longitude' => 73.8713140,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0085',
                'name' => 'Chella Bandi Branch',
                'address' => 'Neelum Road, Chella Bandi, Muzaffarabad AJK',
                'latitude' => 34.393963861480024,
                'longitude' => 73.47161480965188,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Bagh')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Bagh')->first()->region_id,
                'code' => '0086',
                'name' => 'Hari Ghel Branch',
                'address' => 'Opposite To Go Petrol Pump Tehsil Hari Ghel District Bagh, Azad Kashmir',
                'latitude' => 33.9428640,
                'longitude' => 73.6973410,
            ],
            [
                'district_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Mirpur')->first()->region_id,
                'code' => '0087',
                'name' => 'Chechian Branch',
                'address' => 'Main Bazar Chechian District Mirpur, Azad Kashmir',
                'latitude' => 33.0791390,
                'longitude' => 73.7530460,
            ],

               [
                'district_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::without('branches', 'region')->where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0089',
                'name' => 'Rahim Kot Branch',
                'address' => 'Rahim Kot (UC Katkair), Tehsil & District Muzaffarabad, Azad Kashmir',
                'latitude' => 33.0791390,
                'longitude' => 73.7530460,
            ],
        ];

        // Standard operating hours for all branches
        $standardOperatingHours = [
            'monday' => ['09:00', '17:00'],
            'tuesday' => ['09:00', '17:00'],
            'wednesday' => ['09:00', '17:00'],
            'thursday' => ['09:00', '17:00'],
            'friday' => [
                'morning' => ['09:00', '13:00'],
                'break' => ['13:00', '14:30'],
                'afternoon' => ['14:30', '17:30'],
            ],
            'saturday' => ['09:00', '13:00'],
            'sunday' => null,
        ];

        foreach ($branches as $index => $branch) {
            // Add standard operating hours if not already specified
            if (! isset($branch['operating_hours'])) {
                $branch['operating_hours'] = $standardOperatingHours;
            }

            // Add default type if not specified
            if (! isset($branch['type'])) {
                $branch['type'] = 'sub_branch';
            }

            // Add dummy coordinates if not already specified
            if (! isset($branch['latitude']) || ! isset($branch['longitude'])) {
                // Generate coordinates within AJK region (approximate bounds)
                $branch['latitude'] = fake()->randomFloat(6, 33.0, 35.0); // AJK latitude range
                $branch['longitude'] = fake()->randomFloat(6, 73.0, 75.0); // AJK longitude range
            }

            if (! isset($branch['is_24_hours'])) {
                $branch['is_24_hours'] = false;
            }

            if (! isset($branch['show_on_map'])) {
                $branch['show_on_map'] = true;
            }

            if (! isset($branch['map_priority'])) {
                $branch['map_priority'] = $branch['type'] === 'main_branch' ? 10 : 5;
            }

            if (! isset($branch['map_color'])) {
                $branch['map_color'] = $branch['type'] === 'main_branch' ? '#007bff' : '#28a745';
            }

            if (! isset($branch['map_icon'])) {
                $branch['map_icon'] = $branch['type'] === 'main_branch' ? 'bank-main' : 'bank-branch';
            }

            if (! isset($branch['status'])) {
                $branch['status'] = 'active';
            }

            Branch::create($branch);
        }
    }
}
